name: Regular health check
on:
  schedule:
    - cron: '30 * * * *'
jobs:
  backend_ping:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://radiant-spire-58483.herokuapp.com/ping
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
